### ISSUE TITLE
Error cannot import name 'SUPPORT_ON_OFF'  since last HA 2025.1.0b2

### ISSUE THREAD

**Issue by deifel** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#575]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Hello,

since the update to 2025.1.0b2 i get the folowing error on all my maps. Die camera entities does not exist anymore:

`Platform error 'camera' from integration 'xiaomi_cloud_map_extractor' - cannot import name 'SUPPORT_ON_OFF' from 'homeassistant.components.camera' (/usr/src/homeassistant/homeassistant/components/camera/__init__.py)
`

Can anyone confirm this? I have already uninstalled and reinstalled it.

### What version of an integration has described problem?

2.2.1

### What was the last working version of an integration?

2.2.1

### What vacuum model do you have problems with?

Roborock S6, Roidmi Eva and Xiaomi

### What version of Home Assistant do you use?

2025.1.0b2

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.XXX
    token: XXXXXXXXXXXXXX
    username: XXXXXX@gXXX.com
    password:XXXX
    colors:
      color_path: [255, 255, 255]
    draw: ['all']
    map_transformation:
      scale: 1
      trim:
        top: 20
        bottom: 20
        left: 20
        right: 20
    scan_interval: 25
    attributes:
      - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell
Platform error 'camera' from integration 'xiaomi_cloud_map_extractor' - cannot import name 'SUPPORT_ON_OFF' from 'homeassistant.components.camera' (/usr/src/homeassistant/homeassistant/components/camera/__init__.py)
```

**Comment by drkng** [comment]
It seems the same issue: 
Entity camera.xiaomi_cloud_map_extractor (<class 'custom_components.xiaomi_cloud_map_extractor.camera.VacuumCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.ON_OFF: 1>
Reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by PiotrMachowski** [comment]
Duplicate of #505
