### ISSUE TITLE
Camera not working in 2025.1 beta release: ImportError: cannot import name 'SUPPORT_ON_OFF'

### ISSUE THREAD

**Issue by danieldotnl** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#577]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

As of the beta of 2025.1, the camera is not working anymore. Apparantly some constants have been removed from code. See the log added to this issue.

### What version of an integration has described problem?

v2.2.4

### What vacuum model do you have problems with?

roborock s5

### What version of Home Assistant do you use?

core-2025.1.0b5

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: {{REDACTED}}
    token: !secret xiaomi_roborock_token
    username: !secret xiaomi_user
    password: !secret xiaomi_pw
    name: vacuum_map
    country: de
    map_transformation:
      scale: 2
    colors:
      color_robo: [224, 224, 224]
      color_charger: [27, 117, 27]
      color_path: [30, 80, 113]
      color_goto_path: [30, 80, 113]
      color_map_wall_v2: [30, 30, 30]
      color_obstacle: [30, 30, 30]
      color_virtual_walls: [255, 0, 0, 60]
      color_no_go_zones_outline: [255, 0, 0, 60]
      color_no_go_zones: [255, 0, 0, 28]
      color_scan: [0, 0, 0, 0]
      color_map_inside: [0, 0, 0, 0]
      color_map_outside: [0, 0, 0, 0]
      color_grey_wall: [0, 0, 0, 0]
      color_map_wall: [0, 0, 0, 0]
    room_colors:
      16: [240, 178, 122]
      17: [133, 193, 233]
      18: [217, 136, 128]
    draw:
      - all
    sizes:
      charger_radius: 5
      vacuum_radius: 5
    attributes:
      - calibration_points
      - rooms
```

### Errors shown in the HA logs (if applicable)

```shell
Logger: homeassistant.config
Source: config.py:1055
First occurred: 09:09:20 (1 occurrences)
Last logged: 09:09:20

Platform error: camera - cannot import name 'SUPPORT_ON_OFF' from 'homeassistant.components.camera' (/usr/src/homeassistant/homeassistant/components/camera/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 1055, in _async_load_and_validate_platform_integration
    platform = await p_integration.integration.async_get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1108, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1185, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1173, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1098, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1272, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1304, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 18, in <module>
    from homeassistant.components.camera import Camera, ENTITY_ID_FORMAT, PLATFORM_SCHEMA, SUPPORT_ON_OFF
ImportError: cannot import name 'SUPPORT_ON_OFF' from 'homeassistant.components.camera' (/usr/src/homeassistant/homeassistant/components/camera/__init__.py)
```

**Comment by PiotrMachowski** [comment]
duplicate of #505
